name: 01 - Building - Blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: say hello
        run: echo "Hello-world!"
  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed-steps
        run: |
          echo "i will fail"
          exit 1
      - name: Goodbye
        run: echo "Goodbye"